
package ${entity.model.package};

import java.io.Serializable;
import java.sql.JDBCType;
import org.bridje.orm.*;
import org.bridje.sql.*;
import java.util.Objects;
import javax.annotation.Generated;

/**
 * This class represents the ${entity.name} entity.
 * ${entity.description!}
 */
@Generated(value = "org.bridje.orm.srcgen.OrmSourceGenerator", date = "${.now?string("yyyy-MM-dd")}", comments = "Generated by Bridje ORM API")
public interface ${entity.name} extends Serializable<#if entity.baseEntity??>, ${entity.baseEntity.name}</#if>
{
    <#list entity.allWrappedFields as field>
    <#if entity.baseEntity?? && entity.baseEntity.hasField(field.name)>
    @Override
    <#else>
    /**
     * Gets the value of the ${field.name} field.
     * ${field.description!}
     * @return A ${field.javaType} object representing the value 
     * of the ${field.name} field.
     */
    </#if>
    public ${field.javaType} get${field.name?cap_first}();

    <#if entity.baseEntity?? && entity.baseEntity.hasField(field.name)>
    @Override
    <#else>
    /**
     * Sets the value of the ${field.name} field.
     * ${field.description!}
     * @param ${field.name} The ${field.javaType} object representing the value 
     * of the ${field.name} field.
     */
    </#if>
    public void set${field.name?cap_first}(${field.javaType} ${field.name});

    </#list>
}
