
package ${entity.model.package};

import java.io.Serializable;
import java.sql.JDBCType;
import org.bridje.orm.*;
import org.bridje.sql.*;
import java.util.Objects;
import javax.annotation.Generated;

/**
 * This class represents the ${entity.name} entity.
 * ${entity.description!}
 */
@Generated(value = "org.bridje.orm.srcgen.OrmSourceGenerator", date = "${.now?string("yyyy-MM-dd")}", comments = "Generated by Bridje ORM API")
public class ${entity.name} implements Serializable
{
    private final static long serialVersionUID = 1l;

    <#list entity.allWrappedFields as field>
    private ${field.javaType} ${field.name};

    </#list>
    <#list entity.allWrappedFields as field>
    /**
     * Gets the value of the ${field.name} field.
     * ${field.description!}
     * @return A ${field.javaType} object representing the value 
     * of the ${field.name} field.
     */
    public ${field.javaType} get${field.name?cap_first}()
    {
        return this.${field.name};
    }

    /**
     * Sets the value of the ${field.name} field.
     * ${field.description!}
     * @param ${field.name} The ${field.javaType} object representing the value 
     * of the ${field.name} field.
     */
    public void set${field.name?cap_first}(${field.javaType} ${field.name})
    {
        this.${field.name} = ${field.name};
    }

    </#list>
    @Override
    public int hashCode()
    {
        if(get${entity.key.name?cap_first}() == null)
        {
            return super.hashCode();
        }
        return get${entity.key.name?cap_first}().hashCode();
    }

    @Override
    public boolean equals(Object obj)
    {
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        final ${entity.name} other = (${entity.name}) obj;
        return Objects.equals(this.get${entity.key.name?cap_first}(), other.get${entity.key.name?cap_first}());
    }
}
