
package ${model.package};

import java.sql.JDBCType;
import org.bridje.sql.*;
import javax.annotation.Generated;

@Generated(value = "org.bridje.orm.srcgen.OrmSourceGenerator", date = "${.now?string("yyyy-MM-dd")}", comments = "Generated by Bridje ORM API")
public class ${model.name}Types
{
    <#list model.types as type>
    public static final SQLType<${type.javaType}, ${type.readType}> ${type.name};

    </#list>
    static {
        <#list model.types as type>
        ${type.name} = SQL.buildType(
                    ${type.javaType}.class, 
                    ${type.readType}.class, 
                    JDBCType.${type.jdbcType}, 
                    ${type.length?string.computer}, 
                    ${type.precision?string.computer}, 
                    <#if type.parser??>(v) -> ${type.parserCode("v")}<#else>null</#if>, 
                    <#if type.writer??>(v) -> ${type.writerCode("v")}<#else>null</#if>);

        </#list>
    }
}
