/*
 * Copyright 2016 Bridje Framework.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.bridje.orm;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Defines a field as the primary key for the entity's table. This annotation
 * should be used on a single field for each entity. The field annotated with
 * this class will be used as the primary key for the entity.
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface Key
{
    /**
     * If the field is an integer numeric field, setting this to true will
     * result in creating an autoincrement column in the database. Autoincrement
     * columns will be generated by the database and readed upon inserting the
     * entity. Key field with autoincrement should not be modify seens they are
     * managed by the database it self.
     *
     * @return If this field represents an autoincrement column in the database.
     */
    boolean autoIncrement() default false;
}
