<#ftl encoding="UTF-8">

package ${enum.package};

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
import javax.annotation.Generated;

/**
 * This object represents the ${enum.name} enumerator for the ${uisuite.name} Theme.
 * ${enum.description!}
 */
@Generated(value = "org.bridje.web.srcgen.WebSourceGenerator", date = "${.now?string("yyyy-MM-dd")}", comments = "Generated by Bridje Web API")
@XmlType
@XmlEnum
public enum ${enum.name}
{
    <#list enum.constants![] as ct>

    /**
     * ${ct.description!}
     */
    @XmlEnumValue("${ct.value}")
    ${ct.name}("${ct.value}")<#sep>, </#sep>
    </#list>;

    private String value;

    private ${enum.name}(String value)
    {
        this.value = value;
    }

    public static ${enum.name} fromString(String value)
    {
        switch(value)
        {
            <#list enum.constants![] as ct>
            case "${ct.value}":
                return ${ct.name};
            </#list>
            default:
                throw new IllegalArgumentException("No enum defined for this string: " + value);
        }        
    }

    @Override
    public String toString()
    {
        return value;
    }
}
