<#ftl encoding="UTF-8">

package ${uisuite.package};

import java.util.Objects;
import javax.xml.bind.annotation.*;
import org.bridje.web.view.*;
import org.bridje.web.view.controls.*;
import javax.annotation.Generated;

/**
 * Defines a meta information for the current view.
 */
@Generated(value = "org.bridje.web.srcgen.WebSourceGenerator", date = "${.now?string("yyyy-MM-dd")}", comments = "Generated by Bridje Web API")
@XmlAccessorType(XmlAccessType.FIELD)
public class ${uisuite.name}MetaTag implements MetaTag
{
    @XmlAttribute(name = "name")
    private String name;

    @XmlValue
    private UIExpression content;

    @Override
    public String getName()
    {
        return name;
    }

    @Override
    public String getContent()
    {
        return Control.get(content, String.class, null);
    }

    @Override
    public int hashCode()
    {
        int hash = 7;
        return hash;
    }

    @Override
    public boolean equals(Object obj)
    {
        if (this == obj)
        {
            return true;
        }
        if (obj == null || getClass() != obj.getClass())
        {
            return false;
        }
        final ${uisuite.name}MetaTag other = (${uisuite.name}MetaTag) obj;
        return Objects.equals(this.name, other.name);
    }
}
