<#ftl encoding="UTF-8">

package ${uisuite.package};

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.bind.annotation.*;
import org.bridje.web.view.*;
import org.bridje.web.view.controls.Control;
import org.bridje.web.view.controls.UIEvent;
import org.bridje.web.view.controls.UIInputExpression;
import javax.annotation.Generated;
import org.bridje.ioc.Ioc;
import org.bridje.vfs.Path;
import org.bridje.vfs.VFile;

/**
 * Represents a view of the application, views are render by themes and are
 * composed from controls. The views are inmutables so once defined they will
 * stay the same at runtime.
 */
@Generated(value = "org.bridje.web.srcgen.WebSourceGenerator", date = "${.now?string("yyyy-MM-dd")}", comments = "Generated by Bridje Web API")
@XmlRootElement(name = "view")
@XmlAccessorType(XmlAccessType.FIELD)
public final class ${uisuite.name}View extends ${uisuite.name}AbstractView implements WebView
{
    private static final Logger LOG = Logger.getLogger(${uisuite.name}View.class.getName());

    @XmlTransient
    private String name;

    @XmlAttribute(name = "title")
    private String title;

    @XmlElements(
        @XmlElement(name = "meta", type = ${uisuite.name}MetaTag.class)
    )
    private List<MetaTag> metaTags;

    @XmlTransient
    private Map<String, UIEvent> events;

    @XmlTransient
    private Map<String, UIInputExpression> inputs;

    @XmlTransient
    private Set<Class<?>> controls;

    @XmlTransient
    private Set<String> resources;

    @Override
    public List<MetaTag> getMetaTags()
    {
        return metaTags;
    }

    @Override
    public void updateMetaTags(List<MetaTag> metas)
    {
        if (metas == null || metas.isEmpty())
        {
            return;
        }
        if (metaTags == null)
        {
            metaTags = new ArrayList<>();
        }
        metas.stream()
                .filter((meta) -> !metaTags.contains(meta))
                .forEachOrdered(metaTags::add);
    }

    @Override
    public String getTitle()
    {
        return title;
    }

    @Override
    public String getName()
    {
        return name;
    }

    @Override
    public void setFile(VFile file)
    {
        super.setFile(file);
        if(file != null) 
        {
            String viewPath = toViewPath(file.getPath());
            this.name = viewPath;
        }
    }

    private String toViewPath(Path path)
    {
        Path basePath = Ioc.context().find(WebViewsManager.class).getBasePath();
        String viewPath = path.toString().substring(basePath.toString().length());
        viewPath = viewPath.substring(0, viewPath.length() - ".view.xml".length());
        return viewPath;
    }

    @Override
    public Set<String> getResources()
    {
        if (resources == null)
        {
            initResources();
        }
        return resources;
    }

    @Override
    public Set<Class<?>> getControls()
    {
        if (controls == null)
        {
            initControls();
        }
        return controls;
    }

    @Override
    public UIInputExpression findInput(String exp)
    {
        if (inputs == null)
        {
            initInputs();
        }
        return inputs.get(exp);
    }

    @Override
    public UIEvent findEvent(String action)
    {
        if (events == null)
        {
            initEvents();
        }
        return events.get(action);
    }

    private boolean checkIsValidView()
    {
        if(getRoot() != null)
        {
            return true;
        }
        LOG.log(Level.WARNING, "The view {0} does not have a valid root control, it will be ignored.", getName());
        return false;
    }

    private synchronized void initEvents()
    {
        if (events == null)
        {
            if (checkIsValidView())
            {
                Map<String, UIEvent> eventsMap = new LinkedHashMap<>();
                findEvents(getRoot(), eventsMap);
                events = eventsMap;
            }
            else
            {
                events = Collections.emptyMap();
            }
        }
    }

    private synchronized void initControls()
    {
        if (controls == null)
        {
            if (checkIsValidView())
            {
                Set<Class<?>> controlsSet = new LinkedHashSet<>();
                findControls(getRoot(), controlsSet);
                controls = controlsSet;
            }
            else
            {
                controls = Collections.emptySet();
            }
        }
    }

    private synchronized void initResources()
    {
        if (resources == null)
        {
            if (checkIsValidView())
            {
                Set<String> resourcesSet = new LinkedHashSet<>();
                findResources(getRoot(), resourcesSet);
                resources = resourcesSet;
            }
            else
            {
                resources = Collections.emptySet();
            }
        }
    }

    private synchronized void initInputs()
    {
        if (inputs == null)
        {
            if (checkIsValidView())
            {
                Map<String, UIInputExpression> inputsMap = new LinkedHashMap<>();
                findInputs(getRoot(), inputsMap);
                inputs = inputsMap;
            }
            else
            {
                inputs = Collections.emptyMap();
            }
        }
    }

    private void findEvents(Control control, Map<String, UIEvent> eventsMap)
    {
        control.events().forEach((ev) -> eventsMap.put(ev.getExpression(), ev));
        control.childs().forEach((child) -> findEvents(child, eventsMap));
    }

    private void findInputs(Control control, Map<String, UIInputExpression> inputsMap)
    {
        control.inputs().forEach((in) -> inputsMap.put(in.getParameter(), in));
        control.childs().forEach((child) -> findInputs(child, inputsMap));
    }

    private void findResources(Control control, Set<String> resourcesSet)
    {
        control.resources().forEach((r) -> resourcesSet.add(r));
        control.childs().forEach((child) -> findResources(child, resourcesSet));
    }

    private void findControls(Control control, Set<Class<?>> controlsSet)
    {
        controlsSet.add(control.getClass());
        control.childs().forEach((child) -> findControls(child, controlsSet));
    }
}
